# "local" or "aws"
db = "local"
# if db = aws (also set environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY):
# aws_region =

auth="passthrough" # NO AUTHENTICATION !!! see available option(s) below
region = ""
pool_id = ""
issuer = ""
audience = ""
